### ISSUE TITLE
Instantiation-time Cluster selection

### ISSUE THREAD

**Issue by kmpaul** [NCAR/ncar-jobqueue#4]
This is related to comments I made in PR #1.

Currently, the way that `NCARCluster` works is such that the _base class_ of the `NCARCluster` class is determined at _import time_ (i.e., when the `from ncar_jobqueue import NCARCluster` command is executed) based on the hostname where the `Client` is running.  At this time, the methodology for constructing new jobs and scaling the cluster is fixed.

I foresee 2 problems with this:

1. By determining which kind of scheduler you use solely from on the hostname, the user cannot launch jobs on the DAV system _from_ Cheyenne...or vice versa.  You can only launch jobs on the system you are on.  Instead, I think you want to let the user decide _which system they want to launch their jobs on_, regardless of where their `Client` is located.

2. By determining the base class of `NCARCluster` at import time, the user cannot provide any input into the decision process (at least in a clear way...you can do it with configuration variables, environment variables, etc., but that's not as clear).  Also, the base class is determined once, and only once, so that a user cannot decide later to (for example) destroy their cluster and create a new one on a different system.  Instead, I think we want the user to select which kind of cluster they want when they create the `NCARCluster` object (i.e., at _instantiation time_).

I have an alternative approach that still has the "look and feel" of the classic `Cluster` approach, and that is to make `NCARCluster` a "factory class" rather than a true `Cluster` class (in the `jobqueue` sense).  To this one would:

- Not have an `NCARCluster.__init__` method, but instead have an `NCARCluster.__new__` method.
- The `NCARCluster.__new__` method would take arguments that determine what kind of `Cluster` object to create (and possibly set default values for that cluster specific to the NCAR systems).
- The `NCARCluster.__new__` method would return either a `PBSCluster` or a `SLURMCluster` or a `LocalCluster`, depending on arguments given to the method.

In other words, the `type` of the `NCARCluster` would change, depending on the arguments given.  That means the return type would _not_ be an `NCARCluster`.  In that sense, the `NCARCluster` would be a "pseudoclass"...or, simply, a "factory class."

**Note:** You could argue that the `NCARCluster` should just be a function, then, and not be a class at all.  I suppose that I would be fine with that, but I want it to "look and feel" just like the way that users learn how to use `dask-jobqueue` from its documentation.  Namely:

```python
from dask_jobqueue import PBSCluster
cluster = PBSCluster(...args...)

from distributed import Client
client = Client(cluster)
```

This makes `NCARCluster` natural and intuitive to the user.  In particular, a user who is already familiar with `dask-jobqueue` will instantly appreciate what `ncar-jobqueue` is doing, and a user of `ncar-jobqueue` (when faced with a situation where `NCARCluster` won't work for them, like running on a different system) will understand, at least the basics of, how to use `dask-jobqueue` instead.

**Comment by matt-long** [comment]
@kmpaul, I think I agree with your general point that it would be good to move the cluster type selection to instantiation time.

However, your first point
> By determining which kind of scheduler you use solely from on the hostname, the user cannot launch jobs on the DAV system from Cheyenne...or vice versa. You can only launch jobs on the system you are on. Instead, I think you want to let the user decide which system they want to launch their jobs on, regardless of where their Client is located.

Presumes that you can actually create functional DAV clusters from Cheyenne. I don't think this is possible; see [jupyterhub_config #3](https://github.com/NCAR/jupyterhub_config/issues/3).

Additionally, in my view a requirement is that the *same code* works on DAV or Cheyenne with no modification. Indeed, I think this was part of our original motivation for `ncar-jobqueue`. 

I think this requirement implies we don't want to require arguments from the user to determine which cluster type to use. Otherwise, why not call that class directly? Optional arguments would be ok.

**Comment by kmpaul** [comment]
@matt-long While I agree with you that you may not be able to launch a DAV job from Cheyenne now, it has always been the intention that this should work.  So, if it doesn't work, that's a cislhelp ticket that needs to go in.  (Btw, I cannot see https://github.com/NCAR/jupyterhub_config/issues/3.  I suspect I was never given access to that repo.  ...Which has me a little angry right now.)

The idea I am proposing is that the user use `NCARCluster` to specify the system they want the cluster to run on...  That should work without code modification no matter where they are running their client.  If it does not, then we need a cislhelp ticket.  ...Or provide intelligent automation in our code to fall back to sensible options.  Keep in mind that the DAV and Cheyenne systems have different memory and hardware capabilities, so you may not be able to run the same notebook on both systems without code modification _anyway_.

The reason to not call the `PBSCluster` or the `SLURMCluster` classes directly is because we can (as part of `ncar-jobqueue`) set appropriate defaults for the user...and appropriate fall-back behavior depending on the system.  We can implement that logic so that the user doesn't have to worry about it.  In my mind, that is the stronger motivation.

**Comment by matt-long** [comment]
@kmpaul I can confirm you don't have access to that repo, though @andersy005 does. I got access after complaining that CISLhelp didn't know about JHub, so we needed a place to post issues.

If DAV and Cheyenne do become interoperable, then I agree that we want to have (optional) user control. 

`dask-jobqueue` does provide cluster-specific settings. For instance, in the NCAR-pangeo-tutorial config, we have the following.
```yaml
jobqueue:
  pbs:
#    project: NCGD0011
    name: dask-worker
    cores: 36                   # Total number of cores per job
    memory: '109GB'             # Total amount of memory per job
    processes: 9                # Number of Python processes per job
    interface: ib0              # Network interface to use like eth0 or ib0
    queue: regular
    walltime: '04:00:00'
    resource-spec: select=1:ncpus=36:mem=109GB
    job-extra: {-o ${TMPDIR}/, -e ${TMPDIR}/}
    local-directory: /glade/scratch/${USER}/dask-tmp

  slurm:
#    project: NCGD0011
    name: dask-worker
    cores: 1                    # Total number of cores per job
    memory: '25GB'              # Total amount of memory per job
    processes: 1                # Number of Python processes per job
    interface: ib0
    walltime: '06:00:00'
    job-extra: {-C casper, -o ${TMPDIR}/dask-worker.o%J, -e ${TMPDIR}/dask-worker.e%J}
    local-directory: /glade/scratch/${USER}/dask-tmp
```
